language: php
php:
  - 7.1
#  - 7.2
#  - 7.3
#  - 7.4
#  - 5.6
services: mysql # Credentials for mysql based on the documentation https://docs.travis-ci.com/user/database-setup/#mysql
script:
  - git clone --depth=50 --branch=master https://shortpixel-travis-user:3b31cbe9a98a90e7869e69162bf05e2890fff77f@github.com/short-pixel-optimizer/plugin-modules.git ../modules
  - bash bin/install-wp-tests.sh  sptestdatabase root ''
  - composer update
  - bash test.sh
