language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
#  - 5.6 No support for 5.6. PHPUnit 5.6 is not found on Travis machines. PHPUnit5 is no longer supported TODO Remove this line
services: mysql # Credentials for mysql based on the documentation https://docs.travis-ci.com/user/database-setup/#mysql
script:
 - git clone --depth=50 --branch=master $UGAN  ../modules
 - bash bin/install-wp-tests.sh  sptestdatabase root ''
 - composer update
 - bash test.sh
env:
  global:
    - secure: bJlncQ8No+gINxXsO+wko/GDZauTBvWE/OegBh4PGZ7Ak5+8+NANIbrH+l/nQk45QPo6dWAeS9hjoxjja1kI9UHgMV8Ib/o5IZQ1BQM6C27rAC8ux4nKKl8uDB02BfZLLPEm4m12QtHnoWMRNhm6pOKXumliE/xyYqVFcHMF0qsCYvt9lztILeDdEv/AvHWLCcrtBYlnv988eReQs/U+Lu4mwE9LH/6Rr0F9+wyvDpBWuB44LBJAvmjcfMsjcBHd35w6TqyqaCyeq/ID2HUWugDaH4c/g4hNusA3O8nF4yOFDaPLXeJwR4xG4yy8mrewFZquNECKDWgxzw+tAOKXoto+hjP/Q0ZI9bsMYLaJmKC67/BZVG1CMQIWH9wYuR8YrYDpz3fiXPd57qp0GaySjZGyN7sSpSj8p2CkqNZCYKqqMzX9SDnnIveRz3fxx21QVQgFRsHQeTsWdItRsLkSA+hqXh/ryunQHo50C3ko1LhQCwylqWMimYAbINMSK4kNT4vcHcLslXQFP/zxstMcutZTWhBfhvhte0BVjsyThQdnvcT7D4bQg+E0ocnxRxyBTgrf3ULSdJ5Jiy7YY7hyYOv5fQdh3qTQHWQRcWmwy8MqCdZKVkDSZVXWjantGTCHTwJ90IBjKiDuMwuEI0TIwZRuEazKVVSvr2xzB9w6qXw=