language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
#  - 5.6 No support for 5.6. PHPUnit 5.6 is not found on Travis machines. PHPUnit5 is no longer supported TODO Remove this line
services: mysql # Credentials for mysql based on the documentation https://docs.travis-ci.com/user/database-setup/#mysql
script:
 - git clone --depth=50 --branch=master $UGAN ../modules
 - bash bin/install-wp-tests.sh  sptestdatabase root ''
 - composer update
 - bash test.sh
env:
  global:
    - secure: FpEnHW5MjCJPjTMNQtNFZl0LreQMuZmmVDWEt/BqxVx6XdjTo3wrqYUvZRVJho5JtVbMGbFZ8DHPcvueqkN22CEMuOeRvjcds2UXIJdfTuaUQ1G8j9EuR7Je4LqtbuHs6S/3I0PYFzUPYu+eKnE7dSKRLBg1ZfXd1K9T7PrCzbMDPXjE9zGErqAp5S0/FapD4xE/KqV9S8YAsKYVAKpcuYOyF4284qHzZ2JDCFZ51ElxRAxckiysGIhRiGAOK45iVojgwMBQC5nJh6LCX6S7L440rzFMO2G0U+1ShEzw/ew7l5XUsvCntvoIyh3nKJujv3X3NQeGXLPqRkAFZxnP9JZJRixHkLjcFDR9j49oe+huE92WJSTT8HZfkLzsccLeRkOwZUkSua6fXHSi1d766rtk1lf8gJ4aYOpc9XePaeSP+2KS7rYhuF5Ip0zKF6mBTNaxzRZ3Zi6w0wcMeWyXmQhWFUB+cZqXBU8M+kI1IHjh9SkW4rXR7dkqWFjkSQrmq63CdGI2dT/jfQdn55h6O1E7of++qFsP+OlBjdmPzgb6V+8h2l4i9dDDA65ImppPDv7ClqBkzo8HZHRMSFrsxvOGuIG4d7XHPJBgB19OF2xQkbmY0GDsIiDYvu3LTuyIVup3kLU1ajDDs9beRE4gODJ5YXTYQcwRUY6p39q5l7Y=
