language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
#  - 5.6 No support for 5.6. PHPUnit 5.6 is not found on Travis machines. PHPUnit5 is no longer supported TODO Remove this line
services: mysql # Credentials for mysql based on the documentation https://docs.travis-ci.com/user/database-setup/#mysql
script:
 - git clone --depth=50 --branch=master $REPO  ../modules
 - bash bin/install-wp-tests.sh  sptestdatabase root ''
 - composer update
 - bash test.sh
env:
  global:
    - secure: YQWkJRW2Ve8WaPIbDTfjm4fLeTyLak4Rwwg3Lefz/XRvPPxWFKsYx0xG4b4VCLlGPVJkCW3ZaUU0aqXwdL6uoxYbm8RlxbtDsYhRBwP1We97Rv+fgCe/S0bpL5LlYVaddhfk9rNXUiNPoP5S4MwvNRJL1wtg+MALdblFSfQAdrE61hguoLZ3489s/i3DPyGDwiyekwYH0sjBY2yHhCL4slw5w1vhUaAhk5YJfQ6gqnNxsTpulcukqu0c/AmPulQWejDqGX7HGpz2r9BLgOxjIzT6+oFerUS1Qa+se/cEUcCPZoPcBMICyJIyexW+6Xan5d8Sl8uVGCvCQB5IowMZNgr/dB5clx1/+SMEfxDtLEqxXn/KojUfoubG880mOmxm/1NuDckdA3a2l9qQI7S/uPmghdG5bGZ+jL9RoufXZ3+6tme32A6OYxBuaTBMRPWW5S1nhQcRB0X8MO8Y1y2LXvQ+9dcfp6nqq9HDEfc9HkGvO2+nGWY9HwtdoQGYv4Ur53I6tbdJasewNNOODCsOVIN5byC+pr1GR7EyT64lnmPMAGiLbzWhszqbMuj+yc6tUfI61EB3ew9BWvBJjAD+KapgPfybZ3b3dI8g3It+YlyN1I0lQS8Xej4owhIyeNq+aslb6Wgm2Gi4cZYCbIet/ax3/sb0ojRCG1mMh4rIccc=