language: php
php:
  - 7.1
#  - 7.2
#  - 7.3
#  - 7.4
#  - 5.6
services: mysql # Credentials for mysql based on the documentation https://docs.travis-ci.com/user/database-setup/#mysql
script:
  - git clone https://21b957fb08d2dd67d2216b5fed14820e0a6fa82a@github.com/short-pixel-optimizer/plugin-modules.git ../modules
  - bash bin/install-wp-tests.sh  sptestdatabase root ''
  - composer update
  - bash test.sh
